### ISSUE TITLE
No block source available for a growing number of clients

### ISSUE THREAD

**Issue by lionzeye** [reddcoin-project/reddcoin-3.10#104]
A number of clients is having trouble discovering other peers to download blocks from.
This issue will be used to gather info and to track the progress of resolving this issue.
We're starting off by adding more dns-seed nodes and users are encouraged to add links to gist files with relevant parts from their debug.log files.

**Comment by davidmar0003** [comment]
I  hope that's my problem. Mine says no block source and not connected.

**Comment by reddink** [comment]
additional seed nodes added to latest build
https://github.com/reddcoin-project/reddcoin/commit/fafc567b8f1465c7a60df0d22a02a1b6eab3063a

**Comment by reddink** [comment]
Closing
