### ISSUE TITLE
App needs to be multi-threaded, locking the UI thread due to background operations is unprofessional

### ISSUE THREAD

**Issue by 1RedOne** [reddcoin-project/reddcoin-3.10#107]
The ReddCoin Core wallet displays 'Not Responding' far too often in Windows.

The app should be refactored to move slow operations into a separate runspace, lagging the UI like this will reduce user trust.

**Comment by HenryYoung42** [comment]
Wait for the Bitcoin 0.15 based version - Reddcoin Fast :)

**Comment by raid5** [comment]
I'm seeing similar issues on macOS.

**Comment by reddink** [comment]
@1RedOne point noted
Working to bring the pertinent upstream components to improve the user experience
Closing issue
