### ISSUE TITLE
[posv-alpha] Corrupted block database detected after wallet restart. Unable to fix.

### ISSUE THREAD

**Issue by maflcko** [reddcoin-project/reddcoin-3.10#11]
I have a corrupted block database every time I restart my client.

Steps to reproduce:
- $ rm -r .reddcoin/testnet
- $ Downloads/posv/reddcoin/reddcoin-qt -testnet  -addnode=108.174.49.42 &
- [Wait for sync]
- Quit QT
- $ Downloads/posv/reddcoin/reddcoin-qt -testnet  -addnode=108.174.49.42 &
- Answer to "Corrupted block database detected. Do you want to rebuild the block database now?" with "Abort"

**Comment by laudney** [comment]
Which OS?

**Comment by maflcko** [comment]
Fedora 20

**Comment by maflcko** [comment]
It worked fine yesterday, though.

**Comment by laudney** [comment]
did you recompile the wallet using tag 'posv-alpha' or the latest HEAD on posv branch?

**Comment by maflcko** [comment]
I highly doubt I did not use the 'posv-alpha' branch as I followed your instructions at http://redd.it/2a017i

**Comment by maflcko** [comment]
Things that happen when I click "OK" instead of "Abort": http://pastebin.ubuntu.com/7765498/plain/

Just let me know if I can execute some code to collect more information which may help you.

**Comment by laudney** [comment]
could you please paste the relevant error output at the end of debug.log inside the testnet folder when you start the wallet?

**Comment by maflcko** [comment]
I have sent you an email with the full logs yesterday. An excerpt can be found here:
- [After clicking "Abort"](http://pastebin.ubuntu.com/7769323/plain/)
- [After clicking "OK"](http://pastebin.ubuntu.com/7769339/plain/)

**Comment by maflcko** [comment]
I just tried to reproduce today and it seems I am not able to.

**Comment by laudney** [comment]
good to hear and i can't reproduce it either

**Comment by maflcko** [comment]
I can reproduce again as of now.

**Comment by maflcko** [comment]
It seems this only appears very sporadically. If you want me to do debug when it reappears, let me know what to do.

**Comment by laudney** [comment]
i think it happens occasionally after you generated a block that got orphaned. can you check whether you have any Generated transaction that's marked as "Conflicted" or (-1 o 3 confirmation) in the Transactions tab?

**Comment by maflcko** [comment]
Had the same idea this morning but I am doing `rm -r .reddcoin/testnet` (see above) So it's sort of implausible.

**Comment by laudney** [comment]
ah. this problem is fixed if you compile wallet by checking out commit 7ea50d2f019bebb59c111f32bb0e30189881e2de

please give it a try.
