### ISSUE TITLE
Synchronizing with the netwrok

### ISSUE THREAD

**Issue by tekalign2006** [reddcoin-project/reddcoin-3.10#110]
Synchronizing with network 3 years and 24 weeks behind... What is going on? it shows me this message when I open the reddcoin app on my windows 64 laptop. I sent 5000 reddcoin tokens to an address generated by this wallet 5 days ago and haven't gotten the coins yet. Am I going to lose the coins?

**Comment by ghost** [comment]
is this the first time? it takes a while to sync with everything. your coin will be there once you finish syncing.

**Comment by Dutchy-79** [comment]
And it doesn't take 3 years, within 48hrs online it should be done I think.

**Comment by OjhaPrashant** [comment]
I used bootstrap file, it took overnight and now its showing 35 Weeks behind. 
isnt it frustrating that Reddcoin in trying to run a business but there is no fast wallet ?
Its almost 4th day and still Synchronizing

**Comment by mardav12D** [comment]
Please remove me from this thread

**Comment by tekalign2006** [comment]
Hi,
Thank you for  your email. Finally, the wallet looks synchronized. but I don't see my balance of 5000 reddcoins which I sent to my address from Cryptopia exchange. I have the address to which the coins were sent to. But The balance shows 0 coins in my wallet. How can I recover my coins? Please help thank you.


Tekalign Gelan 

    On Friday, January 5, 2018, 1:19:34 PM CST, mardav12D <notifications@github.com> wrote:  
 
 
Please remove me from this thread

**Comment by reddink** [comment]
@tekalign2006 
would seem that the blockchain sync was completed successfully
Closing issue.
FYI Official Reddcoin Core is working on providing faster sync times
