### ISSUE TITLE
Can't get it to work on Raspberry Pi

### ISSUE THREAD

**Issue by Dutchy-79** [reddcoin-project/reddcoin-3.10#111]
I tried 3 manuals and still can't get it to work on my raspberry pi. Any help would be great.

**Comment by lionzeye** [comment]
Have you tried this one? https://github.com/joroob/reddcoin/blob/master/doc/rasp-tut.md

**Comment by Dutchy-79** [comment]
Thanks I'll give that a try

**Comment by bzhang443** [comment]
tried https://github.com/joroob/reddcoin/blob/master/doc/rasp-tut.md, couldn't compile.
stopped at step 6.3 Compile reddcoind (daemon) and reddcoin-cli (client), error as:
In file included from chainparams.h:9:0,
                 from protocol.h:13,
                 from addrman.h:9,
                 from addrman.cpp:5:
bignum.h:56:24: error: invalid use of incomplete type ‘BIGNUM {aka struct bignum_st}’
 class CBigNum : public BIGNUM
                        ^~~~~~
In file included from /usr/include/openssl/crypto.h:31:0,
                 from allocators.h:15,
                 from serialize.h:9,
                 from netbase.h:13,
                 from addrman.h:8,
                 from addrman.cpp:5:
/usr/include/openssl/ossl_typ.h:80:16: note: forward declaration of ‘BIGNUM {aka struct bignum_st}’
 typedef struct bignum_st BIGNUM;
                ^~~~~~~~~
In file included from chainparams.h:9:0,
                 from protocol.h:13,
                 from addrman.h:9,
                 from addrman.cpp:5:
bignum.h: In constructor ‘CBigNum::CBigNum()’:
bignum.h:61:21: error: ‘BN_init’ was not declared in this scope
         BN_init(this);
                     ^
bignum.h: In copy constructor ‘CBigNum::CBigNum(const CBigNum&)’:
bignum.h:66:21: error: ‘BN_init’ was not declared in this scope
         BN_init(this);

**Comment by raid5** [comment]
What's the issue/error?

**Comment by bzhang443** [comment]
https://github.com/reddcoin-project/reddcoin/issues/103  fixed my issue. remember to downgrade openssl, and change 2 pieces of code

**Comment by ghost** [comment]
@raid5 
#103

**Comment by reddink** [comment]
for those watching this thread, have just added a branch for testing/feedback
My testing is limited currently to RaspberryPi 2/Raspian (Jessie)
If you wish to test/validate clone the repo and checkout the arm_support_v2 branch
https://github.com/reddcoin-project/reddcoin/tree/arm_support_v2

**Comment by sassman** [comment]
on PI 3 with raspbian stretch
```
uname -a
Linux raspberrypi 4.9.59-v7+ #1047 SMP Sun Oct 29 12:19:23 GMT 2017 armv7l GNU/Linu
```
with dependencies 
`libssl1.0-dev libboost1.58-all-dev`

branch [arm_support_v2](https://github.com/reddcoin-project/reddcoin/tree/arm_support_v2) configured with
```
./configure --disable-tests LDFLAGS="-L${BDB_PREFIX}/lib/" CXXFLAGS="-I${BDB_PREFIX}/include/ -mfloat-abi=hard -mlittle-endian -munaligned-access -mcpu=cortex-a53 -mfpu=neon-fp-armv8 -O3 --param ggc-min-expand=1 --param ggc-min-heapsize=32768" --enable-sse2=no --with-gui=no
```
builds successfully. **Nice**!

Only thing, that is a bit strange is, that the wallet balance is 0 and all the balance is shown as stake value. Not sure if that is correct.

**Comment by sassman** [comment]
After re-copy the whole wallet from my mac reddcoin app to the PI I'm getting an error like
```
reddcoin-cli getinfo
...
    "errors" : "Warning: The network does not appear to fully agree! Some miners appear to be experiencing issues."
```

**Comment by mathiasdg** [comment]
I tried to install the reddcoin wallet on headless raspberry pi 3 running the latest raspbian lite.

I followed this tutorial: https://github.com/joroob/reddcoin/blob/master/doc/rasp-tut.md

Everything worked pretty fine till the end of step 6. When I try to compile from source  I get a bunch of errors. See here: 
[https://pastebin.com/KSBszNnT](https://pastebin.com/KSBszNnT)

Anyone can help?

**Comment by YavuzzzSelimmm** [comment]
I got it to working on my Raspberry Pi Model 3B.
Instructions are here: https://www.reddit.com/r/reddCoin/comments/8ep06l/staking_reddcoin_core_client_gui_wallet_on_a/.

**Comment by lukaweb** [comment]
Does anyone compiled v2.0.1.2 on raspberry pi? 
At the moment the one and only working seems to be joroob fork (https://github.com/joroob/reddcoin.git)

**Comment by YavuzzzSelimmm** [comment]
> Does anyone compiled v2.0.1.2 on raspberry pi?
> At the moment the one and only working seems to be joroob fork (https://github.com/joroob/reddcoin.git)

Yes. Please see my tutorial on Reddit: https://www.reddit.com/r/reddCoin/comments/a0wn1v/updated_staking_reddcoin_core_client_gui_wallet.
