### ISSUE TITLE
Win 32 setup download not working

### ISSUE THREAD

**Issue by YoFoCrypto** [reddcoin-project/reddcoin-3.10#114]
Just tried to download Win 32 setup but I get message download failed...I've tried the Reddcoin download page at fisrt and then here at Github...same issue...

**Comment by reddink** [comment]
@YoFoCrypto 
Verifying download links are available
New binaries soe 2.0.1.2 are available
https://github.com/reddcoin-project/reddcoin/releases

closing issue as resolved
