### ISSUE TITLE
Integrate with segwit to be ready for Lightnig Network

### ISSUE THREAD

**Issue by medisoft** [reddcoin-project/reddcoin-3.10#116]
It could be one of the best improvements of reddcoin, to integrate segwit.

That way reddcoin will not only be very fast, low power consumption blockchain, but also a very neat way to do transactions and improve the value of the RDD because it could be on the same environment as BTC and LTC into LN.

**Comment by HenryYoung42** [comment]
I am building "Reddcoin Fast" which will a rebasing on Bitcoin 15 with PoSV reintegrated. This will therefore feature SegWit.

**Comment by medisoft** [comment]
Hi!

That Reddcoin Fast will be an upgrade for Reddcoin, a Fork or a new coin?

**Comment by HenryYoung42** [comment]
It will just be an alternative full node implementation operating on the same chain.

**Comment by TechAdeptRDD** [comment]
Issue resolved in latest v4.22.X wllet. Update required (binaries here on github or download.reddcoin.com) Ticket marked done and closed.
