### ISSUE TITLE
Reddcoin maturity for coinage

### ISSUE THREAD

**Issue by medisoft** [reddcoin-project/reddcoin-3.10#118]
Hi! I could not find the amount of coindays required to make a UTXO valid for staking, I read the FAQ, the paper and tried into the code miner.cpp

Is that information in other place?

Thanks!

**Comment by reddink** [comment]
the minimum time is 8 hours
https://github.com/reddcoin-project/reddcoin/blob/773e823dfd74f5d9b3c3f4fbb54d5ba48f778edf/src/chainparams.cpp#L45

**Comment by reddink** [comment]
@medisoft was the answer satisfactory?
Will close off this issue
