### ISSUE TITLE
Add Godex to Exchanges list

### ISSUE THREAD

**Issue by godexdev** [reddcoin-project/reddcoin-3.10#119]
Hello!
Can you please add Godex to your resources/exchanges list.
https://godex.io
Thanks in advance!

**Comment by reddink** [comment]
Thanks
Passing into our website team to add

**Comment by godexdev** [comment]
Thanks!

**Comment by godexdev** [comment]
Hello! 
Can you please tell me how soon Godex will be added to the RDD website?
Thanks!

**Comment by TechAdept** [comment]
https://wiki.reddcoin.com/index.php?title=Exchanges

**Comment by godexdev** [comment]
Many thanks!
Is it possible to add Godex to the main page of RDD website? In the Resources/Exchanges section?

**Comment by godexdev** [comment]
Perhaps on the main page you do not have more space to accommodate new exchangers. 
But, as I detected one of those services no longer exists. Is it possible that Godex will be hosted instead of the service that no longer exists?

**Comment by reddink** [comment]
Have updated main page exchange list with Gobex link

**Comment by reddink** [comment]
Thanks, and let me know if you need anythign more
Closing issue
