### ISSUE TITLE
[posv-alpha] Refresh staking icon more often

### ISSUE THREAD

**Issue by maflcko** [reddcoin-project/reddcoin-3.10#12]
The staking icon does not always represent the current info. The console gives a different output than the icon:

![screenshot from 2014-07-09 13 28 28](https://cloud.githubusercontent.com/assets/6399679/3523674/53aae63a-075d-11e4-8cc7-1d9c0bac1f7e.png)

```
getstakinginfo

{
"enabled" : true,
"staking" : false,
"currentblocksize" : 1000,
"currentblocktx" : 0,
"pooledtx" : 0,
"difficulty" : 35.84874133,
"search-interval" : 1,
"weight" : 0,
"netstakeweight" : 2429127009,
"expectedtime" : -1
}
```

**Comment by laudney** [comment]
the staking icon is only refreshed once every 10 seconds, which is frequent enough for practical purposes.

**Comment by maflcko** [comment]
Hmm, but it took somewhere between 7 and 61 confirmations. And 7 confirmations is more than 10 seconds.

Steps to reproduce would probably be:
- Send all coins to one of your addresses
- Wait until you collect enough age and create a block

Expected result: The Icon turns grey after 10 seconds
Actual result: The icon turns grey after 50(?) confirmations

**Comment by laudney** [comment]
that's expected behavior. after you mint a block which contains a coinstake transaction, the block is not mature until after 50 confirmation. so during the wait for 50 confirmations, it's still considered to be staking.

**Comment by maflcko** [comment]
Still, the output of "getstakinginfo" does not match the one of the icon.

**Comment by laudney** [comment]
getstakinginfo is always up-to-date. information on icon is calculated once every 10 seconds

**Comment by maflcko** [comment]
The screenshot above was taken 7 minutes after I found the block. It says
- I am staking
- I have weight
- Expected time 10h

The output of getstakinginfo after 7 minutes was:
- "staking" : false
- "weight" : 0
- "expectedtime" : -1

**Comment by laudney** [comment]
let me look into this

**Comment by laudney** [comment]
fixed in one of the last few commits. please pay attention and double check when I make the RC1 release this weekend.
