### ISSUE TITLE
Unlock wallet (/w disabling staking) for doing transactions only [Feature Request]

### ISSUE THREAD

**Issue by yczycz** [reddcoin-project/reddcoin-3.10#120]
Since Reddcoin StakeBox is out, is it possible to add the feature to unlock the wallet for spending RDD without doing staking?

The scenario for this would be -- a user has a bunch of reddcoin on a wallet address and does staking with the StakeBox. He/she wants to spend some of the RDD on the same wallet address with his/her desktop computer (without interfering the staking with StakeBox because the private key of that particular wallet address will be in the StakeBox as well as in the desktop computer).

Perhaps I am wrong (I didn't update my knowledge for a long time), and the feature has been implement. Otherwise, the unlock functionality with "stake only" option can provide three combinations:

1. CannotSpend+NoStake (initial state)
2. CannotSpend+Stake (unlocked, "stake only" checked)
3. CanSpend+Stake (unlocked, "stake only" unchecked)

And I believe the 4th item "CanSpend+NoStake" should now be added to the wallet software. What do you think?

**Comment by reddink** [comment]
Main comment on this request is that a user should NOT share the same wallet between 2 devices. There is no synchronisation, particularly if change addresses are generated.

The correct method would be to have seperate wallets, and to transfer funds as needed between the 2.

An analogy would be that one was your bank and the other your wallet in your pocket
