### ISSUE TITLE
source code update wallet RDD on Yobit 

### ISSUE THREAD

**Issue by marco6622** [reddcoin-project/reddcoin-3.10#121]
Hi all, since January 26, the RDD wallet on Yobit has entered maintenance and is still in this state and therefore, it is impossible to receive and send RDD. The customer service has communicated that it is necessary to update the source code of the wallet: the following message of the assistance. Can anyone help or provide for solving this problem that is creating difficulties for many people? Thank you

"Deposit\Withdrawal coin will be available after you upgrade the source code of the wallet. Unfortunately the developers are in no hurry to send you updates
- therefore, in order to avoid the loss of users, the network is not available.
If you have updated the source code of the coin, send us (https://yobit.net/en/maintenance_request/ Free)and we will promptly correct the problem on the coin.
Thank you for contacted the support."

**Comment by lionzeye** [comment]
There are no know issues that would prevent an exchange from running the Reddcoin wallet. If there is indeed an issue, a representative should open a Github issue explaining the details. If it's a security issue: responsible disclosure can be done by PMing me on Reddit: /u/lionzeye

**Comment by marco6622** [comment]
I honestly can not explain them, I'm sorry, I'm not a computer technician. I'm just a customer who transferred so many RDDs from the wallet desktop to the yobit wallet that was under maintenance and that still does not work, reporting what was communicated to me by the assistance. I'm just trying to figure out what their problem is because many people are in my same situation, waiting for 20-day coins. The message (in quotes) I wrote above was the answer from customer support. What does it mean unfortunately I do not know. If I could help more than that, I would do it willingly, but in addition to reporting the situation three times a day to yobit, I can not do it. Thanks again

**Comment by marco6622** [comment]
can you please help me? Can anyone send an alert or update this source code of the currency?

**Comment by nikola7288** [comment]
Marco tell me what password you indicated that would withdraw funds from the purse of the desktop RDD on the purse exchange YOBIT

**Comment by marco6622** [comment]
Hi, thank you but I solved the problem, the founds arrived at their
destination! Regards

2018-02-20 18:34 GMT+01:00 nikola7288 <notifications@github.com>:

**Comment by reddink** [comment]
problem resolved
closing ticket

**Comment by Sonettejvr** [comment]
Hi Marco

> Hi, thank you but I solved the problem, the founds arrived at their destination! Regards 2018-02-20 18:34 GMT+01:00 

How did you solve the problem?  I also sit with the same problem... what did you get the problem fixed?
