### ISSUE TITLE
Problems with rewards

### ISSUE THREAD

**Issue by EnacheLucian** [reddcoin-project/reddcoin-3.10#122]
https://www.icloud.com/numbers/0e33TbtGZdojkyL0S52HV4Ehw#red Users sustain the network because of rewards. I think that I will not do it no more coz in the last month I did not get not one reward! Consuming my computer energy for nothing, pls advice.

**Comment by lionzeye** [comment]
Duplicate #123

**Comment by reddink** [comment]
closing
