### ISSUE TITLE
20GB wallet install on Mac  

### ISSUE THREAD

**Issue by pesto2606** [reddcoin-project/reddcoin-3.10#124]
I've got a small amount of RDD that I want to transfer to a wallet however I just went to download the Mac wallet and its saying that I need 20GB of space to download the RDD blockchain, I've been told the latest version of this should only be 4GB

**Comment by raid5** [comment]
I'm curious where you read the latest is only 4GB?

**Comment by pesto2606** [comment]
I could be wrong but when I posted about my issue above in the reddcoin Reddit another user commented to say it should only be 4GB for Mac wallet downloads.

**Comment by reddink** [comment]
The install instructions mention 20GB for future proofing.
The current install needs about 
4GB for data (blockchain)
100Mb for binaries
