### ISSUE TITLE
How can i import pubkey

### ISSUE THREAD

**Issue by skawhdgjs** [reddcoin-project/reddcoin-3.10#126]
There is no Rpc call for import publickey unlike other altcoin

How can i import publickey ?

**Comment by reddink** [comment]
Could you provide the rpc call you are referring

**Comment by MinwooJ** [comment]
I use importpubkey , importaddress for tracking UXTO without privatkey in other altcoin.
But  I cann't find method to tracking UXTO whitout privatekey

**Comment by skawhdgjs** [comment]
I use importpubkey , importaddress for tracking UXTO without privatkey in other altcoin.
But I cann't find method to tracking UXTO whitout privatekey in reddcoin

**Comment by Bruntsvik** [comment]
Hi

Hey there I tried to import Reddcoin private key to Desktop wallet, But I cannot!

I try this

  importprivkey KEY

Every once give me empty field (after press enter!)
