### ISSUE TITLE
Why does downloading the 4GB blockchain take 26 hours?

### ISSUE THREAD

**Issue by HeRo002** [reddcoin-project/reddcoin-3.10#128]
I don't know if this is the right place to ask this question, but with my Internet connection downloading 4 GB should take 20 minutes, not 26 hours. And why has my (old) CPU been working hard all these hours?

**Comment by HenryYoung42** [comment]
The performance limiting factor with Reddcoin Core 2.1 blockchain sync is rather more on the CPU side than the bandwidth side.  There is a huge amount of number crunching to do - every transaction and every block is re-validated which entails a great deal of very inefficiently implemented (in that version) cryptographic primitives.  That should accelerate significantly when Reddcoin Fast comes out, which will rebase the Reddcoin code base from Bitcoin 0.9 (circa 2014) to Bitcoin 0.16.

Running on a faster CPU makes a proportionate difference also.

**Comment by HenryYoung42** [comment]
Incidentally, loading the blockchain from a local file takes around 24 hours on my 2011 vintage laptop. It's very definitely a CPU limited activity. Open Task Manager and you'll see your CPU spending a lot of time at 100% and the applications user interface responding poorly.

**Comment by HeRo002** [comment]
Thank you for your elaborate answer! 
My laptop is also from 2011, and yes - I could see the CPU working hard in Task Manager, but not all of the time! It seems like a very irregular process.

**Comment by HenryYoung42** [comment]
You will see a dramatic improvement once the code base of Reddcoin moves up to or past Bitcoin 0.12. Previously all the crypto primitives were implemented in the OpenSSL library which is very general purpose but poorly optimised. Bitcoin later moved over to a slimmed down and heavily optimised implementation developed by Pieter Wuille (a veritable technical development god).

**Comment by HeRo002** [comment]
OK! Thanks again.

**Comment by ghost** [comment]
What is the status of this? Syncing with the bootstrap file is still pathetically slow...

**Comment by HenryYoung42** [comment]
It is still an in-progress project which I have not touched for a few months - sorry for that. Real life keeps getting in the way.

**Comment by TechAdeptRDD** [comment]
Current update; Reddcoin Core will be upgrading shortly to electrumx (headers-first optimized) sync. Speed of blockchain sync has tested as much improved. Please download new wallet when available
