### ISSUE TITLE
Reddcoin wont recognize my coins in my wallet

### ISSUE THREAD

**Issue by Spirol9** [reddcoin-project/reddcoin-3.10#130]
finally decided to update my reddcoin wallet i have a back up for it so i updated and added in my wallet but shows i dont have anything i went back to the older version and all my coins show again?? any idea on how to fix?

**Comment by reddink** [comment]
If you copied your wallet.dat file into the reddcoin data directory, that should have been enough.
Could you provide a bit more details on the steps (inc file paths) you did
