### ISSUE TITLE
I unpacked reddcoin-2.0.1.2-linux.tar.gz - Now what?

### ISSUE THREAD

**Issue by HeRo002** [reddcoin-project/reddcoin-3.10#131]
I have unpacked reddcoin-2.0.1.2-linux.tar.gz - Now what? There is no obvious "run me" file. My guess is that I need to execute one of these files: 

reddcoin-2.0.1.2-linux/bin/64/reddcoin-cli
reddcoin-2.0.1.2-linux/bin/64/reddcoind
reddcoin-2.0.1.2-linux/bin/64/reddcoin-qt
reddcoin-2.0.1.2-linux/bin/64/test_reddcoin
reddcoin-2.0.1.2-linux/bin/64/test_reddcoin-qt

But which?

Edit: I already loaded the whole blockchain in the windows version of the wallet. Can I re-use those data here in Linux so I don't need to spend another 26 hours of high CPU?

PS: I use Ubuntu 18.04. The wallet link for ubuntu on https://reddcoin.com/get-started/ did not work in Firefox ESR, but it works in the newest Firefox.

**Comment by ghost** [comment]
It's `./reddcoin-qt` if you want a graphical user interface. Suppose so :)

And yes, you could probably just move the contents from `%APPDATA%\Reddcoin` to `~/.reddcoin`, but then you'd better re-index them while starting the wallet after you copied it: `./reddcoin-qt -reindex`.

Note: this `-index` option is only needed just once. After the wallet is fully started and reindexed, you can leave out that option the next time.

**Comment by HeRo002** [comment]
Thank you! Now I have tried doing that, but reddcoin-qt doesn't seem executable(?) 
Here is a copy of my commands in Terminal:

henrik@Henrik-L570:~$ cd .reddcoin
henrik@Henrik-L570:~/.reddcoin$ dir
blocks	chainstate  db.log  debug.log  peers.dat  reddcoin-qt  wallet.dat
henrik@Henrik-L570:~/.reddcoin$ reddcoin-qt -reindex
reddcoin-qt: command not found

I guess I am still a linux-beginner, so what am I doing wrong here?

**Comment by RobP-git** [comment]
Welcome to linux :) Linux will only execute files from the %path%, not the current directory. This is a big difference to Windows. "./" references the current folder. So if are in /home/me/.reddcoin already, just type "./reddcoind".

If you're on the command line you'll want to use reddcoind and reddcoin-cli.

1) Setup your config file /home/me/.reddcoin/reddcoin.conf
google vi or pico for info on how to edit files in linux

2) Start the server "./reddcoind 2>&1 &"

3) Interact with the server using reddcoin-cli "./reddcoin-cli"

**Comment by HeRo002** [comment]
Now you lost me... I was pointed to reddcoin-qt because it has a GUI. Why do you want me to use the others? Can't I start an application with a GUI from Terminal?

**Comment by ghost** [comment]
Because you said you are new to linux, I _assume_ you have a graphical environment on a desktop PC or laptop. Like the Ubuntu desktop or something like that.

In that case you can use the `./reddcoin-qt` for the GUI if you are not that familiar with the command line or just want to use the GUI because that's easier.
Personally I would only use the commandline if the OS does not have a graphical user interface or in case the resources are somewhat scarce.

**Comment by HeRo002** [comment]
OK. Thank you - but here comes the next problem - from Terminal: 

henrik@Henrik-L570:~/.reddcoin$ ./reddcoin-qt -reindex
./reddcoin-qt: error while loading shared libraries: libQtGui.so.4: cannot open shared object file: No such file or directory

How do I install the missing library?

Update/edit: 
I tried this in Terminal (which didn't work):

henrik@Henrik-L570:~$ sudo apt-get install libQtGui.so.4
[sudo] password for henrik: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libQtGui.so.4
E: Couldn't find any package by glob 'libQtGui.so.4'
E: Couldn't find any package by regex 'libQtGui.so.4'
henrik@Henrik-L570:~$ 

Second edit: 
I don't know why the server is crossing out the above, that I pasted from Terminal?

**Comment by ghost** [comment]
Try installing QT like: `sudo apt install libqtgui4`

**Comment by HeRo002** [comment]
OK. Now reindexing is running! 
Terminal-command: ./reddcoin-qt -reindex
GUI saying: "Reindexing blocks on disk...", "4 years and 10 weeks behind", and "9 active connections to Reddcoin network". 
For some reason it seems the reindexing process has deleted 1.6 GB of the 4.7 GB that was generated before I moved it from Windows 7 to Ubuntu 18.04. 
Thanks for now. :-)

**Comment by ghost** [comment]
Nice! The indexing will take some time, just let it go :)

**Comment by GlassFX** [comment]
I wish someone would just break down and make a video on this!
It's really difficult to pursue a coin, when they can't get a instruction "HOW TO" because this is not as clear as it seems.
HOW CAN ANY INVESTOR TAKE A COIN SERIOUS..... when said coin is happy knowing a wallet install is a damn serious issue.  If they treat investors like this,.. how serious are they about their project?!?!?
MY 2 SATOSHIS

**Comment by HenryYoung42** [comment]
It is more or less the same for Bitcoin on Linux. That's doing ok ;-)
