### ISSUE TITLE
The partner instant exchange SimpleSwap.io

### ISSUE THREAD

**Issue by charlie-selle** [reddcoin-project/reddcoin-3.10#134]
Hi,

I am Nicolas, the manager at SimpleSwap.io, an instant cryptocurrency exchange.

We present a simple and easy-to-use platform that works without registration and limits and allows users to make swaps in just two clicks.

We successfully support RDD on our service for a long time and we have been exchanging RDD for more than 200 coins to our customers. I tried to find contact with your team but without results.

I'm sorry that I invaded here, but maybe you can tell me where I can turn. I would like to make contact so we can have an interaction.

**Comment by MatWaller** [comment]
I Will reach out to someone about this and get them to get back to you,

You could try contacting Jay from the team section on [reddcoin](https://reddcoin.com)

**Comment by MatWaller** [comment]
Closing Issue.

**Comment by TechAdeptRDD** [comment]
ReddCoin no longer supported on SimpleSwap.io. :(
