### ISSUE TITLE
source code upgrade of nlc2 coin wallet on Yobit.io

### ISSUE THREAD

**Issue by ilkanov** [reddcoin-project/reddcoin-3.10#139]
hi. i have deposited some nlc2 coin to yobit. but i have seen that wallet was on maintenance . then i reached support , they asked me to upgrade source code. i really have no idea to do it. anyone has encountered same problem ? and help me ?

**Comment by reddink** [comment]
check-in with the guys on NLC2 project
https://github.com/NoLimitCoin/
They should be able to help you
