### ISSUE TITLE
Reddcoin Wallet's font

### ISSUE THREAD

**Issue by Promethee83** [reddcoin-project/reddcoin-3.10#143]
Good morning, everyone,

Since a few days I opened my portfolio (2.0.1.2) on MacOS Catalina and I have squares instead of numbers and letters...
Do you know where I can download the wallet font?

Thank you very much in advance
![IMAGE 10-07-2019 À 23 30](https://user-images.githubusercontent.com/52762540/61006565-f263d300-a36a-11e9-9e5b-9b8b6c41d422.JPG)

**Comment by reddink** [comment]
Just so it is clear to me,
Was this originally working, and then a change in setting caused the display problem.

**Comment by Promethee83** [comment]
Yes, it has always worked well.

A priori, it was when there was an update of the system that it no longer worked.
I had been asked to download a font but the download was not completed.
Since then, I haven't had the message to download the font anymore...

**Comment by Promethee83** [comment]
I uninstalled the wallet, I reinstalled it, I uninstalled it and deleted all the files, I downloaded the bootstrap (to go faster) but nothing happened.
Yesterday I updated the OS but I still have the same problem.
It would appear that a font is not installed in the system and that the portfolio chooses an unsuitable font.

**Comment by reddink** [comment]
Hi,
It looks like the change to catalina also changed the system default font.
Since Mojave OSx has used 'San Francisco' as the system font

However, Reddcoin is currently configured to use the system default or fall back to 'Lucida Grande' only

Could you check if your system has the 'Lucida Grande' font installed.

**Comment by Promethee83** [comment]
Hi,
It seems that the font is installed (see screenshot 1)
However, I don't see the SanFrancisco font, unless it's the one called SF (see screenshot 2).
When I first started, following the portfolio update, I was asked to download a font (I can't remember which one) which I did but the download didn't work. I repeated the operation several times but there was nothing to do.
So I cancelled the operation and told myself that the next time he started the portfolio he would ask me to download the font again: mistake!
Couldn't one of the fonts be corrupted? Should I download the fonts again?
In any case, thank you very much for your help because I don't know what to do anymore...

![IMAGE 18-07-2019 À 18 13](https://user-images.githubusercontent.com/52762540/61477206-00c77580-a98f-11e9-9e07-2260b6733def.JPG)

![IMAGE 18-07-2019 À 18 15](https://user-images.githubusercontent.com/52762540/61477243-19379000-a98f-11e9-9e63-f3a059f4e5e3.JPG)

**Comment by Promethee83** [comment]
Anny idea to solve the problem ? 😉

**Comment by Promethee83** [comment]
I tried to ask Apple support but no answer yet.
I'm going to wait for the next release (I hope it will be ok)
Moreover I don't stake anymore. The green button is grey but I don't know why because I can't read anything on my wallet

**Comment by ratmat2002** [comment]
I'm having the same problem on Mac OS Catalina latest beta

**Comment by Promethee83** [comment]
Moreover I can't stake anymore... and still have the same problem :-(

**Comment by eldiablonyc** [comment]
you can still stake, just unlock your wallet it still works.  I have the same issue and am currently staking

**Comment by stephen4x** [comment]
The Lucida font is installed but the San Fran is no available hence the same issue as above. VERY frustrating. Wallet is currently unusable.  Luckily I don't need to move anything as this time.. but who knows eh. Hopefully a fix will come.

**Comment by Promethee83** [comment]
I have unlocked my wallet but it still doesn't work. I can't read why...
It is a big problem for us.... I hope too that a fix will come
![screenshot reddcoin](https://user-images.githubusercontent.com/52762540/67481747-c262e600-f662-11e9-9f23-c889d61a45bb.jpg)

**Comment by arshiay** [comment]
i have this problem too 
is there any fix for that?

**Comment by HenryYoung42** [comment]
Works fine on Windows and Linux. If you only have access to MacOs, you could try running the Windows version under Windows emulation.

**Comment by stephen4x** [comment]
<img width="677" alt="Screenshot 2020-02-17 at 00 47 09" src="https://user-images.githubusercontent.com/56839466/74616369-4152c180-511f-11ea-9aae-bd840640494a.png">
 ^ There was a response in another thread (same issue) for anyone who may have missed it.

**Comment by stephen4x** [comment]
download the new release guys! All fixed and working :D. [https://www.reddcoin.com/2020/06/13/reddcoin-core-3-10-0/](url)
