### ISSUE TITLE
letters not show in macos catalina

### ISSUE THREAD

**Issue by arshiay** [reddcoin-project/reddcoin-3.10#144]
hi 
how can i fix this?
<img width="855" alt="Screen Shot 2019-11-25 at 12 21 36" src="https://user-images.githubusercontent.com/20510822/69528522-9e593400-0f83-11ea-80df-22f0913ddcae.png">

**Comment by TechAdeptRDD** [comment]
We have been working on this and will have a confirmed fix release available soon.

**Comment by stephen4x** [comment]
Thanks for the hard work TechAdeptRDD . A few of us patiently waiting 😄

**Comment by thaabitalbertus** [comment]
🤷🏽‍♂️

**Comment by mrlando** [comment]
Any progress on this? It has been almost 4 months...

**Comment by thaabitalbertus** [comment]
Hello,

Thank you for following up. I had given up on the wallet and had not checked.

I have now installed v3.0.1-osx, but I still have the same problem. I have attached a picture of the wallet.  The wallet is unusable. 

I’m very disappointed. 

Thank you
Thaabit

**Comment by HenryYoung42** [comment]
I suggest you try running on Windows or Linux. You can try running the Windows version on osx under Wine or a proper VM. This issue with fonts on osx has existed for years and the developers are clearly not willing to resolve it.

**Comment by thaabitalbertus** [comment]
Hello Henry,

Thank you for your prompt response, which I appreciate. 
 
I think that I’ll dispose of the coins rather than frustrating myself over a poorly conceived OSX wallet.

Thank you for your kind assistance.
Stay safe.
Thaabit

**Comment by TechAdeptRDD** [comment]
In order to accomodate MacOS Catalina changes and new build requirements,
Reddcoin (like many other cryptocurrency projects) has had to do extensive
work to achieve compatibility, and have completed most of the work required
in the last few months along with integrating other components of the
bitcoin 0.10 code base. If it was a simple fix, it would have long since
been released. A version compatible with Mac Catalina should be available
for general use in the next month or so as we complete the required
foundational work for those changes.

**Comment by HenryYoung42** [comment]
Might be an issue with the ancient version of Qt being used referencing a font in a location which is no longer there:
https://www.macworld.com/article/3528553/font-chaos-in-macos-catalina-and-how-to-deal-with-it.html

**Comment by mrlando** [comment]
Thanks for the update @TechAdeptRDD, we will have to wait a little bit longer then.

**Comment by stephen4x** [comment]
woohoo the fix is out! the new release works just fine guys. have it running as normal on my MacBook Catalina . [https://www.reddcoin.com/2020/06/13/reddcoin-core-3-10-0/](url)

**Comment by thaabitalbertus** [comment]
THANK YOU STEPHEN4X! 

It works fine and appears to be slightly faster when booting!
Thank you again. Now I don’t have to fly blind any longer.

Thaabit

**Comment by thaabitalbertus** [comment]
Thanks so much guys!!!!

**Comment by thaabitalbertus** [comment]
Thank you so much to everyone involved!
