### ISSUE TITLE
No network access on MacOs High Sierra 10.13 = v3.0.1.0 does NOT work over VPN

### ISSUE THREAD

**Issue by Th1s1sm3** [reddcoin-project/reddcoin-3.10#147]
Hi Reddcoin,

I recently downloaded the v3.0.1.0-39088ca-beta version of the Reddcoin wallet to my mid 2010 64 bit MacBookPro7,1 13 inch with a 1280x800 display.

Starting the client in the normal way I have for the past 1.5+ years for staking 

now results in no network access for the wallet. So it just sits there as it cannot update the block index. Both UPnP and SOCKS proxy methods have been attempted.

Is there a workaround from the command line perhaps. Google  / Reddit are not much help and I don't know where else to post this.

Thanks in advance.

![20200203 ReddcoinSync](https://user-images.githubusercontent.com/60599930/73642328-7df8d480-46ac-11ea-97de-f22a4b390d43.png)

**Comment by reddink** [comment]
could you try shutting down the wallet and deleting (renaming) the peers.dat file.
location is 
/Users/[USER NAME]/Library/Application Support/Reddcoin

restart the wallet

**Comment by Th1s1sm3** [comment]
Thanks. That made a partial difference. The query "do you want to allow incoming connections" now appears with the splash screen on startup but there is still no network access. The block index cannot update. I have checked the firewall setting and attached a screenshot of network settings in the Reddcoin Client.
![20200207 ReddcoinNetwork](https://user-images.githubusercontent.com/60599930/73991853-5cd40480-4988-11ea-8653-42d0cd1e2c34.png)

**Comment by Th1s1sm3** [comment]
I had a further thought - does the V3 client operate over VPN? I had no drama with V2 and NordVPN for over a year and half.

**Comment by Th1s1sm3** [comment]
Yep, sorry to be so amateur about this... turned off the VPN and Reddcoin v3.0.1 is now synchronising with the network.

Conclusion: Reddcoin v3.0.1.0-39088ca-beta does not work over VPN on MacOS High Sierra 10.13.6

**Comment by Th1s1sm3** [comment]
So, I'm not a novice computer user and I'm not a gun hacker either  - somewhere in the grey inbetween. But the behaviour of v3 is strange on my MacBook Pro to say the least.
- While the wallet is starting / loading it won't connect to the network while the VPN is active.
- So it opens and hangs with no network connection.
- Disconnect the VPN and the network becomes accessible / block index updates / staking is possible.
- Turn the VPN back on and the wallet carries on merrily....

I can't explain it but given I can make the wallet work and have access to my coins I'm closing the issue.

Thanks to the community for your project.
