### ISSUE TITLE
Version 3.0.0 will not close on Windows 10

### ISSUE THREAD

**Issue by freeappmm** [reddcoin-project/reddcoin-3.10#148]
Hi,
when i try to shutdown the client on Windows 10 Build 1909 the process is not closed, it even consumes more and more RAM. I have now waited about an hour after click on File -> Exit. So i have to kill it. After this when i start it next time it will always check the blockchain for all blocks, so after every shutdown and restart, maybe windows updates, i have to wait about 3 days before it is online again...

**Comment by TechAdeptRDD** [comment]
Please upgrade to latest v3.10.0. https://www.reddit.com/r/reddCoin/comments/h88u4j/reddcoin_rdd_core_release_v3100_reddcoin_core/
