### ISSUE TITLE
Installing v3.0.1 on Windows 10 machine (64-bit) & text is trashed

### ISSUE THREAD

**Issue by troyswood** [reddcoin-project/reddcoin-3.10#150]
![photo_2020-02-17_19-09-34](https://user-images.githubusercontent.com/12215211/74700805-58022280-51ca-11ea-94d7-9d88cb09b1ee.jpg)

Installing v3.0.1 on Windows 10 machine (64-bit) & text is trashed (see attached img).

However, the window can be resized from default and then text looks good.

Many ppl may not know this and abandon the install.

**Comment by TechAdeptRDD** [comment]
Please retest with new v3.10.0 wallet and reopen issue if still applicable. https://www.reddcoin.com/2020/06/13/reddcoin-core-3-10-0/
