### ISSUE TITLE
segfault error 4 in libpthread-2.27.so

### ISSUE THREAD

**Issue by matyushkins** [reddcoin-project/reddcoin-3.10#151]
Hi.
reddcoin(x64) is started in docker ubuntu 18.04
Error:
`reddcoind[12850]: segfault at 160 ip 00007fafb4501fa0 sp 00007faf56ffaf58 error 4 in libpthread-2.27.so[7fafb44f8000+1a000]`
container is restart every 30-60 sec(139 code).

`

> Reddcoin version v3.0.1.0-39088ca-beta (2020-01-10 11:32:53 +1100)
> Using OpenSSL version OpenSSL 1.0.1k 8 Jan 2015
> Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010)
> Default data directory /root/.reddcoin
> Using data directory /root/.reddcoin
> Using at most 865 connections (1024 file descriptors available)
> Using 4 threads for script verification
> scrypt: using scrypt-sse2 as detected.
> Bound to [::]:45444
> Bound to 0.0.0.0:45444
> init message: Loading block index...
> Opening LevelDB in /root/.reddcoin/blocks/index
> Opened LevelDB successfully
> Opening LevelDB in /root/.reddcoin/chainstate
> Opened LevelDB successfully
> LoadBlockIndexDB(): last block file = 22
> LoadBlockIndexDB(): last block file info: CBlockFileInfo(blocks=238940, size=123353092, heights=2930642...3166410, time=2019-09-10...2020-02-21)
> LoadBlockIndexDB(): transaction index enabled
> LoadBlockIndexDB(): hashBestChain=ed32745db0e759656c8720e2e6aecaddbd3c3c3df10ecb02cf22587b42f3dadd height=3166410 date=2020-02-21 16:53:44 progress=0.999996
> init message: Verifying blocks...
> Verifying last 288 blocks at level 3
> No coin database inconsistencies in last 289 blocks (650 transactions)
>  block index           28892ms
> Wallet disabled!
> init message: Loading addresses...
> Loaded 0 addresses from peers.dat  0ms
> mapBlockIndex.size() = 3174135
> nBestHeight = 3166410
> setKeyPool.size() = 0
> mapWallet.size() = 0
> mapAddressBook.size() = 0
> ext-ip thread start
> dnsseed thread start
> Loading addresses from DNS seeds (could take a while)
> net thread start
> addcon thread start
> opencon thread start
> msghand thread start
> dumpaddr thread start
> init message: Done loading
> ERROR: GetMyExternalIP() : connection to 91.198.22.70:80 failed
> GetMyExternalIP() received [xxx.xxx.107.48] xxx.xxx.107.48:0
> GetMyExternalIP() returned xxx.xxx.107.48
> AddLocal(xxx.xxx.107.48:45444,4)
> ext-ip thread exit
> Segmentation fault

`

**Comment by matyushkins** [comment]
Additional info: Crash on send on RPC POST data `{"jsonrpc":"2.0","method":"getmininginfo", "params":[], "id":1} and {"method":"getmininginfo","jsonrpc":"2.0","id":"1"}`

**Comment by reddink** [comment]
I am not able to reproduce outside of docker
could you test if the same occurs using getstakinginfo
additionally, if you could provide your docker configuration, i will try and reproduce

**Comment by matyushkins** [comment]
Dockerfile:
> `FROM ubuntu:18.04
> RUN set -o errexit -o nounset \
>     && apt update \
>     && apt install wget net-tools curl libc6 -y \
>     && rm -rf /var/cache/apt/
> ENV COIN_DATA /coin/data
> ENV COIN_VERSION 3.0.1
> ENV COIN_VERSION2 3.0.1
> VOLUME ["/coin/data"]
> 
> RUN set -o errexit -o nounset \
>     && cd /opt \
>     && echo wget "Coin" \
>     && wget -O coin.tar.gz https://github.com/reddcoin-project/reddcoin/releases/download/v${COIN_VERSION}/reddcoin-${COIN_VERSION}-linux.tar.gz \
>     && tar zxvf coin.tar.gz \
>     && mv /opt/reddcoin-${COIN_VERSION}-linux/* /coin/  \
>     && mkdir -p ${COIN_DATA} \
>     && rm -rf /opt/*
> ADD  coin.conf /coin/coin.conf
> ADD  coin.conf /coin/data/coin.conf
> WORKDIR /coin
> HEALTHCHECK --interval=1m --timeout=30s --start-period=10s --retries=3 CMD [ "[ "`curl -o /dev/null -s -w "%{http_code}\n" http://localhost:45443/`" == "401" ]; echo $? " ]
> ENTRYPOINT [ "./bin/64/reddcoind", "-datadir=/coin/data", "-conf=/coin/coin.conf" ]
> EXPOSE 45444 45443
> `

**Comment by TechAdeptRDD** [comment]
Can you please confirm this issue still occurs in newly release v3.10.0? https://www.reddcoin.com/2020/06/13/reddcoin-core-3-10-0/
