### ISSUE TITLE
Reddcoin (liunx) wallet is compiled with a non standard library libQtGui.so.4

### ISSUE THREAD

**Issue by programmingzor** [reddcoin-project/reddcoin-3.10#153]
The linux version of the reddcoin wallet is compiled with a non standard library, therefore it does not runs on all computers. 

**libQtGui.so.4: cannot open shared object file: No such file or directory**

The wallet should not depend on this library. Other coin wallet software wont use this file, and they dont depend on it. This must be fixed. Also **libQtNetwork.so.4**.

Tested:
3.0.1.0-39088ca-beta
compiled at 2020-01-10 11:32:53 +1100

**Comment by reddink** [comment]
Was this the pre-build binary, or you have compiled from source?

**Comment by programmingzor** [comment]
I have downloaded the release from the website at a point of time. 
It seems this is the current version, the last 64 bit linux release available on the website:

md5sum of reddcoin-qt is 947d460fc32890f855b0a7b668b02e55

**Comment by TechAdeptRDD** [comment]
Can you please recheck this issue is resolved with new release v3.10.0? https://www.reddcoin.com/2020/06/13/reddcoin-core-3-10-0/
