### ISSUE TITLE
Wallet not loading

### ISSUE THREAD

**Issue by 240Zed** [reddcoin-project/reddcoin-3.10#154]
Hi - I have been staking for the last 2.5 years and for the last week I have had issues starting the wallet.

See attached screenshots. Any help is appreciated.

OS: Windows 7 64bit.

![Capture01](https://user-images.githubusercontent.com/62552276/77321113-12180d00-6ce8-11ea-8538-42b6c0d4d59d.JPG)
![Capture02](https://user-images.githubusercontent.com/62552276/77321126-16442a80-6ce8-11ea-9512-c140eb9541dc.JPG)

**Comment by 240Zed** [comment]
Debug file attached.
[debug.log](https://github.com/reddcoin-project/reddcoin/files/4369632/debug.log)

**Comment by justinvforvendetta** [comment]
@240Zed did you solve this? 

if not, try wiping your blockchain data in the %appdata% reddcoin directory, except the wallet.dat and try to start it again.

**Comment by 240Zed** [comment]
Got it solved. thanks. Techadpet helped me

**Comment by justinvforvendetta** [comment]
@240Zed awesome, you can close the issue then, im not able to.
