### ISSUE TITLE
version GLIBC_2.15/2.14 not found

### ISSUE THREAD

**Issue by FFMG** [reddcoin-project/reddcoin-3.10#16]
I just pulled the latest binaries from https://github.com/reddcoin-project/reddcoin/releases/download/v1.3.0.0/reddcoin-1.3.0.0-linux.tar.gz and I try and run it I get

```
./reddcoind: /lib64/libc.so.6: version 'GLIBC_2.15' not found (required by ./reddcoind)
./reddcoind: /lib64/libc.so.6: version 'GLIBC_2.16' not found (required by ./reddcoind)
```

Any way to get those built into the binaries, (or where can I locate them)?

Many thanks

FFMG

**Comment by FFMG** [comment]
Further to my comment CentOS uses GLIBC 2.12
Could  Reddcoin be build against GLIBC 2.12?

FFMG

**Comment by laudney** [comment]
You should compile it yourself.

**Comment by FFMG** [comment]
Yeah, I think I might need to.
But there are some openssl issues with CentOS, you need to use openssl-1.0.1f

I would get a warm(er) fuzzy(er) feeling if the file was 'officially' created. 
Especially given the popularity of Centos, (6.5.x and earlier).

FFMG

**Comment by laudney** [comment]
I see your point. Unfortunately CentOS is nowhere near as popular as Ubuntu which is what's used in our gitiban build system for Linux. With everything set up, it only takes one command to compile the daemon and two commands to compile the QT wallet.
