### ISSUE TITLE
"False" information of staked amount

### ISSUE THREAD

**Issue by KayP1988** [reddcoin-project/reddcoin-3.10#161]
Not necessarily a false amount shown, but when I receive a stake it shows the amount staked in total including the dev fund. But when I restart the wallet, the amount is changed back to the amount I personally received. 
Just a small issue I think.

I use the 3.10.1.0 core wallet.

**Comment by reddink** [comment]
you are correct, this is a display issue.
When the wallet is restarted, and the transactions are scanned, it is only adding the stake reward, and not including the dev fund.

**Comment by mmod-max** [comment]
Yes, i experienced the same problem. Had to start the core wallet app with --zapwallettxes=1 to fix the problem.

**Comment by TechAdeptRDD** [comment]
Issue resolved in latest v4.22.X wllet. Update required (binaries here on github or download.reddcoin.com) Ticket marked done and closed.
