### ISSUE TITLE
Trouble or Progress?

### ISSUE THREAD

**Issue by Im2Sexy4myCat** [reddcoin-project/reddcoin-3.10#162]
Hello Reddcoin Development Team,
I have noticed that when Litecoin/Bitcoin based wallets synchronise and generate a "Loading Block" fault, when the wallet is restarted and the wallet informs the user that it is re-indexing the block, no Progress Bar can be seen! This is important so that we know with some certainty, whether the wallet has truly "frozen" and is not operating. The danger is, if a mistake in this judgement is made, the wallet holder can believe the Reddcoin wallet is not working and prematurely close it down, so compounding the issue further. This could "potentially" lead to a situation where the wallet is re-installed, and where the new installation still fails to work. 

Please could this matter be addressed so that we can clearly see a "Progress Bar" during the re-indexing process, so that after several hours of waiting, we can be assured that the wallet is working!

**Comment by TechAdept** [comment]
That is an insightful and useful suggestion. We’ll take a look into that as
a feature for sure.

**Comment by TechAdeptRDD** [comment]
Issue fully resolved in new v4.22 codebase.
