### ISSUE TITLE
Process and Syncing Break.

### ISSUE THREAD

**Issue by Im2Sexy4myCat** [reddcoin-project/reddcoin-3.10#164]
Hello Reddcoin Development Team,
I have noticed that when the Reddcoin wallet closes down, it does so warning the user not to shut Windows down while the wallet is exiting. However, there are "rare" moments when the program will exit and yet still remain alive in the Windows background processes for several minutes.  This can lead anyone who does not know how to check the background Windows processes - to see if Reddcoin has correctly shutdown - to unknowingly and accidentally to close their Windows operating system down while Reddcoin is still working. 

I am convinced this can be the cause for the rare moments when the blockchain indexing can be "fractured" or "broken", so that the Wallet has to rebuild its blockchain. I refer to you to the subsequent problems raised from my former enhancement suggestion - #162, "Trouble or Progress?"

I would suggest the following improvement: - To have an additional program fired, when the Reddcoin wallet is closed down, which shows a splash screen - warning the user that the wallet is still shutting down and not to close down the operating system, until the wallet has properly closed down.

**Comment by reddink** [comment]
Thanks for the suggestion.
Have added to the development list

**Comment by TechAdeptRDD** [comment]
Bump.
