### ISSUE TITLE
I am noticing this issue. After launching the wallet I am not able to view the wallet in the desktop.

### ISSUE THREAD

**Issue by hasanora** [reddcoin-project/reddcoin-3.10#168]
I having a problem with the wallet. I using the latest wallet. I was working fine. Since yesterday I am noticing this issue. After launching the wallet i am not able to view the wallet in the desktop.
![reddcoin](https://user-images.githubusercontent.com/13524004/92133658-a37ec580-edd6-11ea-9951-02b4f9c454b7.png)
 However, I checked the task manager that showed the process is running. I rebooted that machine multiple times. Please advice if there is any solution.
Running on win10 pro

reddcoin

**Comment by reddink** [comment]
could you provide debug.log to help determine what is happening

**Comment by hasanora** [comment]
Please see attached log.

[debug.log](https://github.com/reddcoin-project/reddcoin/files/5175733/debug.log)

**Comment by reddink** [comment]
Thanks for providing, there is nothing obvious in the log file (no errors).
Does the wallet eventually display?? Example if you are letting is run for 5 minutes or more.

**Comment by hasanora** [comment]
I tried revising antivirus software still same issue.

**Comment by HenryYoung42** [comment]
https://bitcoin.stackexchange.com/questions/50901/what-is-an-obfuscation-key

**Comment by reddink** [comment]
> I tried revising antivirus software still same issue.

Thanks for checking AV.
So I have also been doing a bit of researching regarding GUI display issues, and have had a couple of hits on potential identical issues logged elsewhere.

https://github.com/dogecoin/dogecoin/issues/1400
https://github.com/bitcoin/bitcoin/issues/10709

In both cases, shutting down the wallet and then deleting a reg key seems to resolve the problem
[HKEY_CURRENT_USER\Software\Reddcoin\Reddcoin-Qt]

Could you please try the suggested, and report back

the long term fix is to update the method of saving/restoring the windows layout (which is being introduced into the next version)

**Comment by hasanora** [comment]
@reddink awesome this fixed the issue. I am able to see the wallet displaying in the desktop.

**Comment by TechAdeptRDD** [comment]
Issue closed. Resolved and fix included in next build.
