### ISSUE TITLE
[Question] Spend unconfirmed?

### ISSUE THREAD

**Issue by maflcko** [reddcoin-project/reddcoin-3.10#17]
I am unable to spend unconfirmed change. Is this a bug or a feature considering that it is possible to do in bitcoin?

**Comment by bjorn** [comment]
I see "Options -> Wallet -> Spend unconfirmed change (experts only)", which is disabled by default. I don't know why this is an expert feature, though.

**Comment by maflcko** [comment]
I have it turned on but it does not work somehow. Could you please try it and tell me if it is working for you? (For me the change always pops up as "Unconfirmed")

**Comment by maflcko** [comment]
It just "fixed itself" by the switch to PoSV
