### ISSUE TITLE
Nonexistent RPC calls return HTML rather than JSON

### ISSUE THREAD

**Issue by HenryYoung42** [reddcoin-project/reddcoin-3.10#170]
When an invalid RPC call is made, for example to find out if zmq is supported using getzmqnotifications, the resulting error message is returned in HTML rather than JSON. This is at odds with pretty much every other Bitcoin derived implementation, and one assumes is connected with the introduction of the REST API with the wrong or a common error handler being called.

**Comment by HenryYoung42** [comment]
Correction - if the call is made with an incorrect username, the error returned is HTML rather than JSON.

**Comment by reddink** [comment]
Thanks @HenryYoung42 will add this to the next release

**Comment by TechAdeptRDD** [comment]
Issue resolved in latest v4.22.X wllet. Update required (binaries here on github or download.reddcoin.com) Ticket marked done and closed.
