### ISSUE TITLE
Both the White Paper and the FAQ Paper point to a 404

### ISSUE THREAD

**Issue by onionman0x** [reddcoin-project/reddcoin-3.10#172]
white paper: http://www.reddcoin.com/papers/PoSV.pdf
FAQs paper: http://www.reddcoin.com/papers/PoSV_FAQ.pdf

both return 404 not found :(

**Comment by onionman0x** [comment]
also http, but the website autoredirects so thats ok

**Comment by onionman0x** [comment]
also the last sentence in "Development Process" reads "Bitcoin".

"`Tags` are created regularly to indicate new official, stable release versions of Bitcoin."

**Comment by TechAdept** [comment]
https://redd.love/assets/doc/Redd-Paper.pdf

https://redd.love/assets/doc/PoSV-v2-FAQ.pdf

https://redd.love/assets/doc/Redd-Book.pdf

Above are accurate links. Also, ReddCoin.com is being rebuilt. Where
specifically did you see those links, if they need to be corrected?

-TA
