### ISSUE TITLE
transaction continues invalid

### ISSUE THREAD

**Issue by trifarashi** [reddcoin-project/reddcoin-3.10#173]
i need help. i've been trying to send my RDD from my reddcoin wallet to another wallet (bittrex wallet and another reddcoin wallet).
but all my transaction ID is not exist in blockchain. i try several methods including increasing the fee but nothing change.

first transaction : 
Status: 728 confirmations
Date: 27/3/2021 17:29
To: RjdiUjVYN7PNwrwDidZzbHf6wxEFP1qH93
Debit: -10.00000000 RDD
Net amount: -10.00000000 RDD
Transaction ID: ed3364ae59fdb67bc8b55117eb2c902801d9ae7fda5477e5ceee445e758022a7-000

2nd :
Status: 562 confirmations
Date: 27/3/2021 21:16
To: RjdiUjVYN7PNwrwDidZzbHf6wxEFP1qH93
Debit: -1.00000000 RDD
Transaction fee: -0.00100000 RDD
Net amount: -1.00100000 RDD
Transaction ID: 2fc0bb89e6fec2457beb42d3b6549be083904a0d1e0134d200e15cf23cf1d76a-000

3rd : 
Status: 66 confirmations
Date: 28/3/2021 09:37
To: RYw12oHoNp7CZRAdVsp52Z38HQBp4bUY5B
Debit: -5.00000000 RDD
Transaction fee: -0.00100000 RDD
Net amount: -5.00100000 RDD
Transaction ID: 8732bfc0ebb12cfa5d6114716e77e0e43af52e51a8e27ae0f1c122bd4162ab1b-000

4th: 
Status: 27 confirmations
Date: 28/3/2021 10:38
To: RihjHz7MEiVd33e4457xzbY5nz5AyTqg2Z
Debit: -1.00000000 RDD
Net amount: -1.00000000 RDD
Transaction ID: a79ee1058aaf61a9fcc9c12c27a49defa0ecf50f457ded4db6f795cefc2a0fb2-000

**Comment by YavuzzzSelimmm** [comment]
Do you still have issues?

**Comment by YavuzzzSelimmm** [comment]
@trifarashi 
Do you still have issues?
