### ISSUE TITLE
new user - available field v stake field

### ISSUE THREAD

**Issue by Twlicker** [reddcoin-project/reddcoin-3.10#175]
Hi,

I installed the Reddcoin Core Wallet. It is fully synced and my Reddcoins are showing up.  I've unlocked it staking only.  Hovering over the green upward arrow estimates a reward in 16 days.

I'm just confused by the "available" field and the "stake" field.   My Reddcoins are currently all showing up in the "available" field, but does that mean they are staking or available to stake?   Or should they all be in the "stake" field for staking, or is that field for the rewards only?

Cheers, Tom

**Comment by reddink** [comment]
Good question!
The "Available" field represents the total amount of coins that are spendable from your wallet.
The "Staking" field represents the total amount of coins that have been allocated for generating a stake reward.

So when staking, as you are now...
All your coins should be available,
If you generate a stake, the funds used to create the stake transaction will be deducted from the "Available" coins field until they have fully matured (50 blocks). That is, you will need to wait for your stake to mature before it becomes spendable
The "Stake" field should now display the total coins that were allocated for the stake transaction.

Regards

**Comment by Twlicker** [comment]
Thanks Reddink!  That makes sense.  So it looks like I'm doing it correctly then.  Happy staking!

**Comment by reddink** [comment]
Yes, the green status symbol is the main indicator that you are staking..

Stake On!!
