### ISSUE TITLE
[minor] Coin control copy behavior

### ISSUE THREAD

**Issue by maflcko** [reddcoin-project/reddcoin-3.10#18]
In the coin control pup-up I am unable to copy any amount with the copy-method provided by the UI (right click) given that the amount is greater than 1000.

The buggy behavior is that the copy-method terminates at the first space character (Large amounts are separated in groups of three e.g. `73 851 984.432789 RDD` so it only copies `73` in this case.)

Due to missing testnet coins I could not try with Bitcoin/Litecoin but it seems this is a great opportunity to do an upstream commit as well.

**Comment by MathyV** [comment]
This will be integrated in the bigmerge-new branch.

On August 11, 2014 9:51:00 PM CEST, MarcoFalke notifications@github.com wrote:

> Fixed by
> https://github.com/bitcoin/bitcoin/commit/7007402956579ace12d45cdcfae908802d3d6b6d
> in bitcoin. I can't do the merge, though.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/reddcoin-project/reddcoin/issues/18#issuecomment-51831142

## 

Sent from my mobile phone
