### ISSUE TITLE
Daemon startup error handling

### ISSUE THREAD

**Issue by samvaughton** [reddcoin-project/reddcoin-3.10#19]
Whilst integrating 1.3 into the reddwallet, I came across the rebuild blockchain bug.. When receiving this error from the daemon child process (stderr) I get this:

> Error opening block database.\n\nDo you want to rebuild the block database now?                   > \nreddcoind-linux-32: db/version_set.cc:803: leveldb::VersionSet::~VersionSet():              > Assertion `dummy_versions_.next_ == &dummy_versions_' failed.\n

Considering there could be other errors etc, this is a hard way to parse a daemon error message. Perhaps change this into a JSON format or atleast provide a decodable message in the string such as

```
[error:0001]
```

Where the number indicates what type of error with a code list. Preferably JSON though eg:

``` json
{
    "error": true, 
    "message": "Error opening block database", 
    "code": 0001
}
```

Thoughts?

**Comment by MathyV** [comment]
I don't agree that there should be JSON on the stderr. Perhaps we can make it available through an RPC call but that depends on where in the startup process we are.

Also, this is a result of an assert and shouldn't even happen in release mode, I'll have to look at what is going on here in more detail first.

**Comment by samvaughton** [comment]
I don't mind the implementation just need be able to accurately identify
the error and display an appropriate message if the daemon doesn't get far
enough for RPC.

Sam Vaughton

**Comment by MathyV** [comment]
Don't work on this until bigmerge is done

**Comment by laudney** [comment]
Can you just display this message in whole if it appears?

**Comment by samvaughton** [comment]
Yeah, most of it isn't very user friendly but I can try and do that for now.
