### ISSUE TITLE
Daemon getinfo extra parameters (locked & encrypted state)

### ISSUE THREAD

**Issue by samvaughton** [reddcoin-project/reddcoin-3.10#20]
It would be nice to display the status of the wallet's encryption and locked states. For the encryption state I have to make a dirty call and I don't like having to do it this way as I want to keep it quite efficient due to the possibility of the daemon being on the raspi etc...

For the wallet locked state.. I don't have a way of knowing unless I call `walletlock` and check for its error code (-17 RPC_WALLET_ALREADY_UNLOCKED) which is also another hack for a simple true/false.

Any possibility of adding two parameters to `getinfo`?

``` json
{
    ...
    "encrypted": true,
    "locked": false
}
```

Or something similar?

**Comment by MathyV** [comment]
Fixed in commit f1eba23c17300a631dd95e6f0d953c0f74103dbf
