### ISSUE TITLE
Huge fees in bigmerge-new branch

### ISSUE THREAD

**Issue by MathyV** [reddcoin-project/reddcoin-3.10#21]
When playing with the old bigmerge branch I observed huge fees (like 10 times the actual transaction amount) being charged. Needs to be checked before we can ever merge to master.

**Comment by laudney** [comment]
Can you still reproduce this on bigmerge-new?

**Comment by MathyV** [comment]
I haven't tested it yet but I also didn't change anything so do keep an eye out when reviewing anything fee related.

On August 26, 2014 5:13:54 PM CEST, laudney notifications@github.com wrote:

> Can you still reproduce this on bigmerge-new?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/reddcoin-project/reddcoin/issues/21#issuecomment-53436900

## 

Sent from my mobile phone

**Comment by TechAdeptRDD** [comment]
Stale issue. Issue resolved in latest v4.22.X wllet. Update required (binaries here on github or download.reddcoin.com) Ticket marked done and closed.
