### ISSUE TITLE
Report for total interest gained for the wallet (total coins staked)

### ISSUE THREAD

**Issue by bugnuker** [reddcoin-project/reddcoin-3.10#34]
I am requesting a feature that will report the total coins that have been earned for a wallet.

This would work 100% like a bank, or a 401k would work.
You can go to your bank account and see the total interest earned. Weather it's been spent or not, you can get a total of all the money you've earned on that account.

I would love the same feature in the wallet. I need this for accounting purposes, and I'm sure other users would also love this feature so they can know what amounts in interest they are earning with their wallets. Just like a bank account does. They send statements, and it shows how much interest you earned. Same thing, same idea, same concept. 

I understand if the PK's are removed from the wallet, this total could be lost. I understand there could be some difficulty with this, for example, I'm not sure if this is tracked at the block chain level or the wallet level. So if someone restored a wallet with just PK's, they might not have the right total anymore.

But this would be just like a bank account as well. If I earned 50.00$ interest over 2 years at my bank, and I withdraw them all and move to another bank account, the total interest would reset. I'm not sure how you want to deal with that.

If you have any question, please let me know.

Thanks!
-Shane (ReddAPI)

**Comment by bigreddmachine** [comment]
Shane,

You should be able to see a full detailed history of transactions, including mining and staking income.  For accounting purposes, minted income is not considered interest.  It is considered payment, just like with mining.  This is because you are essentially being paid to help secure the network.  So you would need to consider it just like regular income.
- Mike

**Comment by MathyV** [comment]
I think this should be an RPC call which has a time range as parameter (which you can set to 0 for all time) so you can get the amount of staked coins over a certain period of time.

**Comment by bugnuker** [comment]
Mike,

While I agree with your terminology, I still would like to see a RPC call to get this number. 

There is currently no way to track this "income" so I can do things with it, like paying users of the service I host.

**Comment by bigreddmachine** [comment]
Fair enough!  I think it's a cool feature idea myself.  I just wasn't thinking about it from that perspective when I read "accounting".  In the meantime, I think you can download a .csv file with all transactions from your wallet and sort out Minting ones.

**Comment by laudney** [comment]
Available now in 4754463e91196e98a9859cccebd27f328a33cf87: getinterest [start] [end]
