### ISSUE TITLE
Bitcoin core

### ISSUE THREAD

**Issue by MathyV** [reddcoin-project/reddcoin-3.10#38]
Bitcoin rebranded their wallet to "Bitcoin Core" a while back. See their release notes:

https://bitcoin.org/bin/0.9.0/README.txt

While I don't really agree that you need to do this to make a distinction between the client and the network, I do think we might need to look at it from the point of view of the social wallet and other platforms we're launching.

Let's discuss

**Comment by reddcoin** [comment]
Isn't the wallet called Reddwallet? I'm not sure I understand your point, can you elaborate?

**Comment by MathyV** [comment]
Reddcoin Core it is
