### ISSUE TITLE
MenuBar Icon with options

### ISSUE THREAD

**Issue by PaulBunYawn** [reddcoin-project/reddcoin-3.10#42]
As discussed here, http://www.reddit.com/r/reddCoin/comments/2cq4ls/can_we_please_get_this_in_a_future_update/

Ideas for information displayed could include

-staking info 
-total coins 
-wallet locked or unlocked 
-network connection 
-info on if client is up to date
-quick wallet feature which if clicked copies a default wallet address to clipboard

**Comment by msphair** [comment]
Can we also get the option to make the icon grey scale?
