### ISSUE TITLE
Wrong OS X binary for v1.3.1.1

### ISSUE THREAD

**Issue by raid5** [reddcoin-project/reddcoin-3.10#43]
https://github.com/reddcoin-project/reddcoin/releases/tag/v1.3.1.1

I just downloaded the OS X build from there and it appears to be v1.3.1.0 still.

**Comment by msphair** [comment]
Either that or the `CLIENT_BUILD` variable https://github.com/reddcoin-project/reddcoin/blob/master/src/version.cpp#L64 isn't being updated properly.

**Comment by laudney** [comment]
Fixed
