### ISSUE TITLE
Negative expected stake time

### ISSUE THREAD

**Issue by stevenroose** [reddcoin-project/reddcoin-3.10#48]
I just noticed this. I have very little coins, so I expect this to be an integer overflow. Are you using regular integers or BigIntegers?

![40d083813550adc423348976a8508b8e](https://cloud.githubusercontent.com/assets/853468/4023344/35dbdb42-2b88-11e4-93d2-f2e5024785b0.png)

**Comment by laudney** [comment]
Fixed in 68f9c32bf48ec357818491eea7cc7589d1124c3f
