### ISSUE TITLE
Unsanitized "Expected Stake Date/Time" labels

### ISSUE THREAD

**Issue by msphair** [reddcoin-project/reddcoin-3.10#52]
They aren't sanitized for bad values resulting in this when the program is first started:

![screen shot 2014-08-28 at 11 44 22 am](https://cloud.githubusercontent.com/assets/1900880/4073710/f55ff086-2e97-11e4-8d6b-6abe0c475d29.png)

**Comment by laudney** [comment]
Fixed. Thank you for the report.
