### ISSUE TITLE
reddcoind on bigmerge branch cannot start on Mac

### ISSUE THREAD

**Issue by laudney** [reddcoin-project/reddcoin-3.10#54]
Assertion failed: (!pthread_mutex_lock(&m)), function lock, file /usr/local/include/boost/thread/pthread/recursive_mutex.hpp, line 110.
Abort trap: 6

**Comment by laudney** [comment]
Fixed.

**Comment by nanocoinorg** [comment]
How did you fix this issue, I'm running into a similar issue on a different fork. I have been trying to track down your commit that fixed it but having trouble locating it. Any help is appreciated.
