### ISSUE TITLE
Reference to outdated OpenSSL version in build-osx.md

### ISSUE THREAD

**Issue by raid5** [reddcoin-project/reddcoin-3.10#57]
In the homebrew section it mentions:

> You should see OpenSSL 1.0.1e 11 Feb 2013

This should probably be changed to mention 1.0.1e as a minimum acceptable version (if that is in fact the min). As an example, currently I have `1.0.1h 5 Jun 2014` on my system, which is also a valid version.

**Comment by laudney** [comment]
please make a pull request
