### ISSUE TITLE
running on OSX for a while messes up the social wallet

### ISSUE THREAD

**Issue by msphair** [reddcoin-project/reddcoin-3.10#59]
The node-webkit Helper process is at constant high CPU usage.

![screen shot 2014-08-30 at 5 46 57 pm](https://cloud.githubusercontent.com/assets/1900880/4099445/e351c27c-305c-11e4-86e5-77b73c8e7ac5.png)

possibly related. The orange refresh icon doesn't go away.

![screen shot 2014-08-30 at 5 45 36 pm](https://cloud.githubusercontent.com/assets/1900880/4099441/c558a7cc-305c-11e4-8af8-c3b4c304bfa5.png)

restarting the wallet solves both of these issues.

**Comment by ghost** [comment]
How do I get off of this reddcoin list thing?.   I do not want all these emails with this stuffl

**Comment by msphair** [comment]
I think this has something to do with OSX's sleep cycle. Seems to happen when Reddwallet's been running and I wake the computer up.

**Comment by TechAdeptRDD** [comment]
Issue resolved in current builds v3.0.x. Issue closed.
