### ISSUE TITLE
Importaing wallet.dat from qt to social

### ISSUE THREAD

**Issue by Hubert-Maci** [reddcoin-project/reddcoin-3.10#64]
I copied over the my wallet.dat from the qt to the social and it seems that one of my recive address is actually my polinox address. I tried to transfer rdd from cryptsy to my wallet using that address and crpytsy posted a tx id, after a couple hours of troubleshooting and talking with hoppi i noticed that the amounts sent to that address corresponded to my transactions to polioniex so i logged in and there was my rdd. It seems that somehow my address i sent to in the past where showing up in my recive address list!

**Comment by laudney** [comment]
Could you please try the following? Start your QT-wallet with the wallet.dat in question and send me all the _names_ of accounts returned by RPC call _listaccounts_

Please remove the account balance from the output for your own privacy. Thanks!

**Comment by samvaughton** [comment]
Hi omgnaro, any update? Would like to get this fixed as soon as possible :)

**Comment by laudney** [comment]
I cannot reproduce it.
