### ISSUE TITLE
Check some commits

### ISSUE THREAD

**Issue by MathyV** [reddcoin-project/reddcoin-3.10#70]
Mostly check if OS X build still works

20d4bb7fc9c7a4e7b51e407619112b7a8a40d3e4
9cb45caed7d9e62f8b767f33a0e94b0005776f56
f5b222000215d491ce4eedb301cf57ac6f59f7ce
2c8740f9cc189f02ce2129a404f61b5cd1fa0e14
e48c646ca139e7bc70f8605cda68f9c6a9a077a8
380e10e70f4adaf6326cca52e159fab8881aff3a
4c621c2ee2a9e6ad5fabb0c98ef283c6880efdff

**Comment by laudney** [comment]
Compiles fine on Mac OS X.
