### ISSUE TITLE
reddcoind crashes on getstakinginfo

### ISSUE THREAD

**Issue by ghost** [reddcoin-project/reddcoin-3.10#81]
Everytime I'm running getstakinginfo, the daemon crashes. This happens with either a locked or unlocked wallet (with both stakingonly=true/false) .

Output (command: strace reddcoind -printtoconsole):
ThreadRPCServer method=getstakinginfo
 <unfinished ...>
+++ killed by SIGFPE +++
Floating point exception

OS: CentOS 6.6 (32 bit)
Reddcoin version v1.4.0.0-unk-beta (2014-10-27 08:31:52 -0400) 
Using OpenSSL version OpenSSL 1.0.1j 15 Oct 2014

**Comment by iisurge** [comment]
Same issue here. Im on centOS 6.5 and running ./reddcoind getstakinginfo cause daemon crash and
Floating point exception

**Comment by TechAdeptRDD** [comment]
Not replicable in current builds (v3.0.x). Issue closed.
