### ISSUE TITLE
Add file bootstrap.dat.xz - 1.4.1

### ISSUE THREAD

**Issue by danielgarciabsb** [reddcoin-project/reddcoin-3.10#82]
Please, can you add a bootstrap.dat.xz file for each release?

It really helps users for starting a new wallet and its better for the network health.

Thanks in advance!

**Comment by reddcoin** [comment]
Hi,

bootstrap.dat.xz was added to 1.4.1 release.

thanks

**Comment by danielgarciabsb** [comment]
Thank you! I love you! <3
