### ISSUE TITLE
Reddcoin wallet not recognize some urls.

### ISSUE THREAD

**Issue by cryptoapi** [reddcoin-project/reddcoin-3.10#83]
Reddcoin wallet not recognize some urls.

1) html link work correctly - 
&lt;a href=&#39;reddcoin:RbjQA3FfY371Djayp6iqy4JubWV8DztFZU?amount=195.9769&amp;label=Payment&#39;&gt;Test1&lt;/a&gt;

2) wallet ignore &#39;amount&#39; - 
&lt;a href=&#39;reddcoin:RbjQA3FfY371Djayp6iqy4JubWV8DztFZU?amount=42195.9769&amp;label=Payment&#39;&gt;Test2&lt;/a&gt;

**Comment by laudney** [comment]
Fixed in 73e0ccfaa3513535cb8d81a2d896b674876d5058.
