### ISSUE TITLE
bootstrap is out of date

### ISSUE THREAD

**Issue by Stoner19** [reddcoin-project/reddcoin-3.10#84]
I've created a zipped bootstrap.dat that will sync to block 258900. Due to the file size it's being shared as a .torrent and I will continue to seed indefinitely. In the meantime I'll continue to find a reliable service where I can upload a large file for free, as the file is just over 1GB (857MB zipped). 
.torrent can be downloaded here: https://mega.nz/#!3BE0TCgb!L0HiDRqmpXL5tIE_toH83nxljRJEQcbnwLIMF_MbI28

**Comment by Erkan-Yilmaz** [comment]
Thanks.
Here (1) seem to be newer (2) files?
It might be worthwhile to help each other ?

(1) https://www.reddcointalk.org/topic/646/unofficial-bootstrap-dat-thread-updated-every-two-weeks-or-three
(2) Last update: 12/18/2015

**Comment by Stoner19** [comment]
Thanks for the suggestion, Erkan-Yilmaz. I've updated the .torrent file and updated the thread on reddcointalk.org.

https://www.reddcointalk.org/topic/606/updated-bootstrap/

**Comment by Stoner19** [comment]
actually, since they're keeping up on it I don't see a need for my bootstraps anymore.
