### ISSUE TITLE
🆘 🆘 🆘 🆘 build on MACOS ,got ERROR "Undefined symbols for architecture x86_64"

### ISSUE THREAD

**Issue by followtheart** [reddcoin-project/reddcoin-3.10#86]
using:

> Qt 4.8.7
> boost 1.6.0
> db 4.8
> Clang x86_64
> OSX 10.11 EI Captian
> 
> ```
> clang: warning: argument unused during compilation: '-pthread'
> Undefined symbols for architecture x86_64:
>   "Db::verify(char const*, char const*, std::ostream*, unsigned int)", referenced from:
>       CDBEnv::Verify(std::string, bool (*)(CDBEnv&, std::string)) in db.o
>       CDBEnv::Salvage(std::string, bool, std::vector<std::pair<std::vector<unsigned char, std::allocator<unsigned char> >, std::vector<unsigned char, std::allocator<unsigned char> > >, std::allocator<std::pair<std::vector<unsigned char, std::allocator<unsigned char> >, std::vector<unsigned char, std::allocator<unsigned char> > > > >&) in db.o
>   "boost::program_options::to_internal(std::string const&)", referenced from:
>       boost::program_options::detail::basic_config_file_iterator<char>::getline(std::string&) in util.o
>   "boost::program_options::detail::common_config_file_iterator::common_config_file_iterator(std::set<std::string, std::less<std::string>, std::allocator<std::string> > const&, bool)", referenced from:
>       boost::program_options::detail::basic_config_file_iterator<char>::basic_config_file_iterator(std::istream&, std::set<std::string, std::less<std::string>, std::allocator<std::string> > const&, bool) in util.o
> ld: symbol(s) not found for architecture x86_64
> clang: error: linker command failed with exit code 1 (use -v to see invocation)
> make: *** [Reddcoin-Qt.app/Contents/MacOS/Reddcoin-Qt] Error 1
> ```
> 
> Any help? thx a lot 🆘 🆘 🆘 🆘

**Comment by reddink** [comment]
This bitcoin thread should point you in the right direction. There is a description on the problem, and the resolution. Please let me know how you get on.
https://github.com/bitcoin/bitcoin/issues/3228

**Comment by followtheart** [comment]
Found Solution [Here!](https://github.com/ezredd/reddcoin/blob/d594ec71d9cbee1c15cba15daaf42ca14cfc54c1/contrib/homebrew/build-reddcoin-qt.osx)
using

```
qmake  -spec unsupported/macx-clang-libc++ reddcoin-qt.pro
```

Thx :bow:

**Comment by reddink** [comment]
Thanks for providing a response, the build process is improved in the later version (to be released)
