### ISSUE TITLE
QT does not build clickable Icon, but can be launched from terminal

### ISSUE THREAD

**Issue by Stoner19** [reddcoin-project/reddcoin-3.10#87]
I was able to successfully `git clone` the new repo and compiled it just fine, however there is something wrong with the QT. It either doesn't build right, or the system can't properly read the file type. I can't double-click it like other QT wallets, however if I launch `./redddcoin-qt` from the terminal it opens the QT wallet just fine. 

You can see from this screenshot that the QT doesn't properly display as it should.
<img width="858" alt="screen shot 2016-08-14 at 9 35 21 pm" src="https://cloud.githubusercontent.com/assets/8030643/17668754/0cd90804-62c8-11e6-8ecf-f74c9e107adf.png">

If I try to double click it this is what I get:
<img width="484" alt="screen shot 2016-08-14 at 9 38 34 pm" src="https://cloud.githubusercontent.com/assets/8030643/17668775/2df11946-62c8-11e6-8d5e-a68344134e61.png">

 Any thoughts on what might be going on here? This is a fresh OS install of Ubuntu 14.04 LTS.

**Comment by reddink** [comment]
Thanks @Stoner19.
What is missing in the .desktop from the installation.
in BItcoin space, this is quite a manual process of editing and copying files around.

I have updated the installation directions

https://github.com/reddcoin-project/reddcoin/commit/02572a635ea6d56eca1434d54202cf365340479d Update Debian installation instructions

**Comment by Stoner19** [comment]
Perfect, thank you for updating the documentation in order to build the `.desktop` app.
