### ISSUE TITLE
important info displayed in the wallet (message of the day, ...)

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [reddcoin-project/reddcoin-3.10#91]
It'd be great if the wallet can display important info (1),
not every user will check forum, social media and so on :-(

Such a (text) field should be self-containable, that means, should not require the user to start the browser to read all. e.g. to make it less possible to trace the user and his wallet (IP, ...)

Who can generate text to be displayed in the wallet?
E.g. the community and/or the current project devs can create multisig adresses, so it will be assured no spam and such gets through. And the text to be displayed is queried from the blockchain then

(1) e.g. like the wallet upgrade from v1.4 to v2.0, or when a poll is upcoming, ...

**Comment by reddink** [comment]
There is an alert system in the wallet already, which, even in bitcoin case, is not used for every update notification.
That said, an effective method to notify end users is warrented

**Comment by TechAdeptRDD** [comment]
Current alert system defunct; master key not available. Possible to evolve code to add new key for functionality in future. Issue closed.
