### ISSUE TITLE
Mac binary not signed with valid key

### ISSUE THREAD

**Issue by pingofchaos** [reddcoin-project/reddcoin-3.10#92]
Says "unidentified source"

**Comment by reddink** [comment]
How are you checking?
codesign -dv /path_to_app/reddcoin-2.0.0.0-osx-signed.dmg
or 
codesign -dv --verbose=4 /path_to_app/reddcoin-2.0.0.0-osx-signed.dmg
for more details

Also since you are not downloading this form the apple store your security should allow apps from Mac App Store & identified developers

**Comment by pingofchaos** [comment]
It would only launch if security is set to all sources allowed.
Says its from an unidentified source.

**Comment by reddink** [comment]
If you run the above command in  a terminal what is the response output?

**Comment by pingofchaos** [comment]
$ codesign -dv --verbose=4 /Applications/Reddcoin-Qt.app
/Applications/Reddcoin-Qt.app: code object is not signed at all

**Comment by reddink** [comment]
and if you run it on the dmg
(only the dmg is signed currently)

**Comment by pingofchaos** [comment]
Identifier=reddcoin-2.0.0.0-osx
Format=disk image
CodeDirectory v=20200 size=308 flags=0x0(none) hashes=1+6 location=embedded
Hash type=sha256 size=32
CandidateCDHash sha256=41106cc6c950b6235c4f1c3d30fa60d514fd080f
Hash choices=sha256
CDHash=41106cc6c950b6235c4f1c3d30fa60d514fd080f
Signature size=8856
Authority=Developer ID Application: John Nash (Q6ZYKJ3NR2)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=06/08/2016 16:00:44
Info.plist=not bound
TeamIdentifier=Q6ZYKJ3NR2
Sealed Resources=none
Internal requirements count=1 size=180

But that is pretty pointless, why don’t you sign the executable?

**Comment by reddink** [comment]
In my test environment, the install process works without raising the warning message.
There are a number of OSx installs already, with yours being the first reported issue on install..
Will revise the signing process for OSx deployment.

**Comment by FlorianWendelborn** [comment]
Same issue here, the .app inside the .dmg from the official website is from an unidentified developer.

**Comment by TechAdeptRDD** [comment]
As of v3.10.0 (https://www.reddcoin.com/2020/06/13/reddcoin-core-3-10-0/) Mac binary is now digitally signed.
