### ISSUE TITLE
Update Litecoin

### ISSUE THREAD

**Issue by oritwoen** [reddcoin-project/reddcoin-3.10#93]
This project is a fork Litecoin but I see that it is not the current version. Among other things, the following error has been corrected in Litecoin (appears when compiling): 

https://github.com/litecoin-project/litecoin/commit/2ede6b7142cb57c422126722f845b36da7d3c4ef

```
In file included from net.cpp: 24: 0:
/usr/include/miniupnpc/miniupnpc.h:62:1: note: DECLARED here
```

I will be grateful for updated fork or patch so that the compilation work correctly :)

**Comment by reddink** [comment]
The current release is now a fork of Bitcoin,
Unfortunately, one is not able to update the github details to reflect that :)

The current build was tested using miniupnpc 1.6 (original)

To resolve the error looks like a trivial fix.

Let me take a look

**Comment by reddink** [comment]
I have just pushed the following commit (81b71123e94ec06c5733cc25c2bb5c9624113259) onto master branch (which also contains a few extra fixes)

**Comment by oritwoen** [comment]
This error no longer displays but now appear other: x Screenshot terminal attached.

![zrzut ekranu z 2016-11-26 07-31-18](https://cloud.githubusercontent.com/assets/18102267/20638566/011592b0-b3ab-11e6-8562-0b18b5b04c4c.png)

**Comment by reddink** [comment]
This is an issue with the newer versions of boost and compiling with c++11
Referencing against the issue on bitcoin. https://github.com/bitcoin/bitcoin/commit/a2b04ddfe6452e7d6274f4096bf3f2aee695a6d9

I can patch this in tonight,

**Comment by reddink** [comment]
I have pushed this update to my personal Reddcoin repo first.
https://github.com/reddink/reddcoin
Can you test it against your system?

**Comment by oritwoen** [comment]
It works a little better but still in one place, now a little later, there are problems with the make.

System:
Fedora 25

**Comment by reddink** [comment]
What is the error now reported?

**Comment by oritwoen** [comment]
`./autogen.sh`

![zrzut ekranu z 2016-11-28 13-15-55](https://cloud.githubusercontent.com/assets/18102267/20668143/8d098d58-b56d-11e6-9cee-74eee8cb79d8.png)

`make`

![zrzut ekranu z 2016-11-28 13-20-20](https://cloud.githubusercontent.com/assets/18102267/20668153/a009846c-b56d-11e6-9784-066604371cc8.png)

**Comment by reddink** [comment]
Thanks for that.
The first screen is ok.. these warnings are expected

Second screen, 
The warning is triggered in the version of boost you have installed (1.61?) 
https://github.com/libbitcoin/libbitcoin/issues/582

It is a known issue and should be resolved in boost 1.62

These should be warnings only, there must be an error also in the output

**Comment by oritwoen** [comment]
You're right, there is a fault. Nothing else appears.

![zrzut ekranu z 2016-11-29 11-53-33](https://cloud.githubusercontent.com/assets/18102267/20707210/c9ea686a-b62a-11e6-87d9-2800f10ab0f6.png)

**Comment by reddink** [comment]
Ok, compiling with QT5 support. The error relates to QT5 build hardening
can you run configure with the following CXXFLAGS="-fPIC"
./configure CXXFLAGS="-fPIC"

in the current Reddcoin configure, it is using -fPIE as default.
I will need to pull the updated configure scripts from bitcoin to pull into our build

**Comment by oritwoen** [comment]
Hmm, I checked this. Not work. I used  `./configure CXXFLAGS="-fPIC"`. Makefile contains fPIC instead fPIE but error is the same.

**Comment by reddink** [comment]
Ok.. thanks for testing.
I have found the relevant commits on bitcoin..
They will need a bit of work to pull into Reddcoin.. stand-by

**Comment by reddink** [comment]
Pulling the relevant build updates is going to take longer than expected.
Can you try running:
make clean
./configure CXXFLAGS="-fPIC" CFLAGS="-fPIC" 
make

**Comment by oritwoen** [comment]
Clean git repository https://github.com/reddink/reddcoin and  `./configure CXXFLAGS="-fPIC" CFLAGS="-fPIC"` the error this same. 

No hurry about it. Take care of more important matters, and to find the time to come back to this, I prefer to compile own wallets but currently I use the downloaded binaries for Linux so it's okay.

**Comment by oritwoen** [comment]
Problem solved.

` ./configure CXXFLAGS="-fPIC" CFLAGS="-fPIC" ` – add fPIC on root folder Makefile but not change **./src/qt/Makefile**. 

I edited **./src/qt/Makefile CXXFLAGS** and manually change fPIE to fPIC.

Btw, please update official branch with previous commit: https://github.com/reddink/reddcoin/commit/2ab654109b69a69c1f4197d4727011afab7d7440

And maybe update ./configure to work with all makefiles not only root?

**Comment by reddink** [comment]
Thanks, glad you got it working. Will make these changes

**Comment by davidmar0003** [comment]
Thanks   I hope I can get this to work. If not I'll be back.

**Comment by Sylk** [comment]
This ticket should be closed.
