### ISSUE TITLE
feature: voting/polls

### ISSUE THREAD

**Issue by Erkan-Yilmaz** [reddcoin-project/reddcoin-3.10#94]
With polls, community decisions can be measured!

**use cases** could be:
 - where to spend funds on
 - what kind of actions to do in a situation (like guidelines)
 - ...

**simplified steps** for brainstorming:
1. users can vote via their wallets (e.g. options like: Yes, No, Abstain (A); or other definable  #answers)
2. there has to be decided on a _criteria_ how the votes count: by balance (that would mean that whales could easily swing a poll), ...
3. a vote will cost something so people can't spam, ...
4. the vote result after the poll must be saved. so everyone can review past decisions

This feature could start first with command line voting, and later a UI could be added (or via external scripting). And then it could be made more pretty, e.g. showing the result as a pie chart

(A) Abstain would be important to legitimate the poll. E.g. when a poll has not many voters by share, ... it could be questioned. E.g. people were in vacation, hospital and couldn't participate

**Comment by TechAdeptRDD** [comment]
Will be added to roadmap for discussion and inclusion. Issue closed.
