### ISSUE TITLE
tip functionality integrated with Twitter/Facebook/Instagram & Reddit? 

### ISSUE THREAD

**Issue by ghost** [reddcoin-project/reddcoin-3.10#98]
when will you integrate the tip function with Twitter/Facebook/Instagram & Reddit?

**Comment by HenryYoung42** [comment]
There are existing tipbots for Twitter and Reddit which you may use today. Improved decentralised tipping will be integrated in the future following the release of Redd-ID. No specific date is being given for this other than the Q3 2017 rough guideline.

**Comment by GreyEcologist** [comment]
Where is the code? Not seeing any work getting done. Why would people invest a team that is AWOL?

**Comment by HenryYoung42** [comment]
Good question - I left the team a couple of months ago ;-)

**Comment by reddink** [comment]
Not all code is on public display.
And some is undergoing closed alpha testing.

Some team members have a lot to contribute, while those who don't move on.
Such is the cycle.

**Comment by TechAdeptRDD** [comment]
Code to date has been made pubic under relevant repos. Work continues. Issue being closed.
